In [2]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray=arr[0:2,1:3]
print(subarray)

[[2 3]
 [5 6]]


In [4]:
Reversed_array=arr[::-1]
print(Reversed_array)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [6]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[4])
print(arr[-1])
print(arr[1:4])
print(arr[arr>25])
print(arr[[1,3]])

10
50
50
[20 30 40]
[30 40 50]
[20 40]


In [7]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,0])


print(arr[1,2])

1
6


In [9]:
 import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [12]:
import numpy as np
result1=np.vstack((arr1,arr2))
print(result1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [13]:
import numpy as np
result2=np.dstack((arr1,arr2))
print(result2)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [14]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
result=np.split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]
